# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: 生成贪吃蛇

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: aelassas/snk/svg-only@main
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: images/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: main
          author_email: mobbbb.top@gmail.com
          message: "Generate Contribution Snake"
